# Generated by Django 5.2 on 2025-04-15 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cro', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialidades.especialidades')),
            ],
        ),
    ]
