# Generated by Django 5.2 on 2025-04-15 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('tratamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em andamento', 'Em andamento'), ('finalizado', 'Finalizado')], max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamentos.tratamento')),
            ],
        ),
    ]
